### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by sylcjl** [szsdk/biblatex-gbt77142005#3]
我是新人，想请教一下这个要如何安装？
使用的是Mac OS X，以安装完全版MacTex，
但一直无法CTAN以及Tex Live Utility找到您的包。
有其他的安装方式吗？

已试过从zip档解压缩直接放入
/usr/local/texlive/2016/texmf-dist/tex/latex/biblatex-gbt77142005
但还是没用

如果可以，麻烦您说明一下完整的安装流程。
急需！

**Comment by szsdk** [comment]
不需要安装，直接放在主文件所在的目录下即可。
让后在导言区通过
```
\usepackage[
backend = biber, style=gbt77142005 ,utf8,
giveninits = true, sortgiveninits = true
]{biblatex}
```
调用即可。
