### ISSUE TITLE
Where to put the files

### ISSUE THREAD

**Issue by ShixingWang** [szsdk/biblatex-gbt77142005#4]
不好意思，我是LaTeX小白，请问一下这些文件要放在TeXlive的哪个文件夹下面呢？谢谢

Excuse me, I have not learned much about LaTeX. May I ask which fold should I put these files in the TeXlive directory? Thanks a lot

**Comment by szsdk** [comment]
就是你的.tex文件夹下

**Comment by ShixingWang** [comment]
非常感谢
